### ISSUE TITLE
Add Linting Front End (ES Lint)

### ISSUE THREAD

**Issue by MutegekiHenry** [BuildForSDG/Team-269-Frontend#17]
**Action Required**
Configure ES Lint for React, with AIR bnb style guide

**Comment by MutegekiHenry** [comment]
For guidance on this you can follow this [article](https://medium.com/@samailabalap/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-4d9936897f03)

**Comment by MutegekiHenry** [comment]
Go to VS- code extensions and search for ES Lint and install it, thats if you hadn't

**Comment by luigimorel** [comment]
Thanks. Will do so. Are you okay with writing tests.

Because I'm trying to get the hang of them and I don't seem to be making a
steady fast response.


---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by MutegekiHenry** [comment]
I am also learning on the job in that department @morelmiles
