### ISSUE TITLE
[FEATURE] Create Mockup/Layout of the application

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Frontend#3]
**Action Required**
Come up with a layout for the application. Menu items, components, This should be based on the user stories and data variables for urban population slum dwellers

**Comment by MutegekiHenry** [comment]
which design tool are you using @morelmiles

**Comment by luigimorel** [comment]
@MutegekiHenry  I am using draw.io. I use Windows 8.1 so I can't use Adobe XD

**Comment by MutegekiHenry** [comment]
> @MutegekiHenry I am using draw.io. I use Windows 8.1 so I can't use Adobe XD

could you kindly share a link to the designs
