### ISSUE TITLE
[FEATURE] Implement Login Functionality

### ISSUE THREAD

**Issue by MutegekiHenry** [BuildForSDG/Team-269-Frontend#36]
**Is your feature request related to a problem? Please describe.**
Yeah, currently a user(enumerator) cant fully be logged in. Front end not talking to backend

**Describe the solution you'd like**
When a user navigates to the login page, and they fill up their details, they should be logged in into the system if the use the right credentials

**Comment by onabright** [comment]
@MutegekiHenry Let me fix this.

**Comment by MutegekiHenry** [comment]
It's actually not a back-end issue.. the current implementation of the front end doesn't query back end. just page designs @onabright
