### ISSUE TITLE
[FEATURE] Review User Stories

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Frontend#4]
**Action Required**
Evaluate user stories that have been defined and prioritize what needs to be implemented.

**Comment by MutegekiHenry** [comment]
@onabright can i get access to the defined User stories?

**Comment by onabright** [comment]
@MutegekiHenry check the document you shared where we were brainstorming ideas for the project.

**Comment by MutegekiHenry** [comment]
Oh yeah, let me check that out
