### ISSUE TITLE
[FEATURE] Design Landing Page

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Frontend#6]
**Action Required**
Build the landing page for SlumData. It should have:

-  Navigation bar with links to all other features of the app (login, signup, about, dashboard)
- Footer

**Comment by MutegekiHenry** [comment]
Code or just a design ui? @onabright

**Comment by MutegekiHenry** [comment]
@morelmiles do we have a design for this page? am not so good at designing mocks.. but i can implement something and we see how to improve that

**Comment by onabright** [comment]
@MutegekiHenry code. Don't worry about the mockup for now.

**Comment by MutegekiHenry** [comment]
Let me cook up something
