### ISSUE TITLE
[FEATURE] Add Component Files to /src

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Frontend#8]
**Action Required**
Add scaffolding for different components. e.g. home, signup, signing, dashboard, etc

**Comment by MutegekiHenry** [comment]
@morelmiles could we kindly have this

**Comment by luigimorel** [comment]
Okay. Let me do that today.

I just didn't want to make one giant PR.


---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by MutegekiHenry** [comment]
remember to rebase your branch so that the current chenges in develop reflect in your branch

**Comment by MutegekiHenry** [comment]
Of course after pulling the new changes in develop

- ` git checkout develop`

- `git pull`

- `git checkout your_branch`

- `git rebase develop`

**Comment by MutegekiHenry** [comment]
@morelmiles I think we can let this go... since for every new component, a developer will create these folders and files
